import { Bot } from 'mineflayer';
import { CommandBuffer } from './Commands';
export declare class UserInterface {
    private readonly bot;
    private readonly program;
    private readonly screen;
    private readonly taskBox;
    private readonly activeBox;
    private readonly logBox;
    private readonly inputBox;
    private readonly tasks;
    private readonly processes;
    private cmdReady;
    readonly commandBuffer: CommandBuffer;
    constructor(bot: Bot);
    addTask(task: string): number;
    getTask(index: number): string;
    removeTask(index: number): void;
    addProcess(process: string): number;
    getProcess(index: number): string;
    removeProcess(index: number): void;
    chat(username: string, message: string): void;
    info(message: any): void;
    warn(message: any): void;
    error(message: any): void;
    log(message: string): void;
    enterCommand(message: string): void;
    finishCommand(): void;
    private resizeBoxes;
}
